---
- name: Install and configure VNC server
  hosts: all
  become: true
  vars:
    vnc_user: "runner"  # Change to your user
    vnc_display: ":1"
    vnc_port: "5901"
    vnc_geometry: "1280x800"
    vnc_depth: "24"

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install Xfce desktop and goodies
      apt:
        name:
          - xfce4
          - xfce4-goodies
        state: present

    - name: Install TightVNC server
      apt:
        name: tightvncserver
        state: present

    - name: Ensure .vnc directory exists
      file:
        path: "/home/{{ vnc_user }}/.vnc"
        state: directory
        owner: "{{ vnc_user }}"
        group: "{{ vnc_user }}"
        mode: '0755'

    - name: Set VNC password (non-interactive)
      shell: |
        echo "password" | vncpasswd -f > /home/{{ vnc_user }}/.vnc/passwd
      args:
        executable: /bin/bash
      become_user: "{{ vnc_user }}"

    - name: Set secure permissions on VNC password file
      file:
        path: "/home/{{ vnc_user }}/.vnc/passwd"
        owner: "{{ vnc_user }}"
        group: "{{ vnc_user }}"
        mode: '0600'

    - name: Create xstartup script for Xfce
      copy:
        dest: "/home/{{ vnc_user }}/.vnc/xstartup"
        content: |
          #!/bin/bash
          xrdb "$HOME/.Xresources"
          startxfce4 &
        owner: "{{ vnc_user }}"
        group: "{{ vnc_user }}"
        mode: '0755'

    - name: Start VNC server (on display {{ vnc_display }})
      shell: "vncserver {{ vnc_display }} -geometry {{ vnc_geometry }} -depth {{ vnc_depth }} -localhost no"
      args:
        executable: /bin/bash
      become_user: "{{ vnc_user }}"
      environment:
        USER: "{{ vnc_user }}"
        HOME: "/home/{{ vnc_user }}"

    - name: Display connection information (for manual use)
      debug:
        msg: |
          VNC Server is running on display {{ vnc_display }} (port {{ vnc_port }}).
          Connect using a VNC viewer to {{ ansible_host }}:{{ vnc_port }}.
          Note: You will need to use a tunneling service like 'cloudflared' to expose this port to the internet.
